<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="SwiftBets.BuildingBlocks.Observability" />
    <PackageReference Include="SwiftBets.BuildingBlocks.Web" />
    <ProjectReference Include="../SwiftBets.Steward.Infrastructure/SwiftBets.Steward.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Content Include="../../transcripts/*.json" LinkBase="transcripts" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
