name: ci

on:
  push:
    branches: [main]
    tags: ['v*']
  pull_request:

permissions:
  contents: read

jobs:
  dotnet:
    uses: remonenaidoo/swiftbets-platform/.github/workflows/dotnet.yml@main
    with:
      images: '[{"name": "swiftbets-steward", "dockerfile": "deploy/SwiftBets.Steward.Api.Dockerfile"}, {"name": "swiftbets-steward-migrator", "dockerfile": "deploy/SwiftBets.Steward.Migrator.Dockerfile"}]'
    permissions:
      contents: read
      packages: write
      security-events: write
